export const ErrorCodeEnum = {
  // 🔄 General Errors
  ALL_FIELDS_REQUIRED: "ALL_FIELDS_REQUIRED",
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_ACTION: "INVALID_ACTION",
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // 👤 User-related
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_CREATE_FAILED: "USER_CREATE_FAILED",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  USER_PROFILE_UPDATE_FAILED: "USER_PROFILE_UPDATE_FAILED",
  USER_DELETE_FAILED: "USER_DELETE_FAILED",
  USER_EMAIL_NOT_VERIFIED: "USER_EMAIL_NOT_VERIFIED",
  USER_PHONE_NOT_VERIFIED: "USER_PHONE_NOT_VERIFIED",
  USER_NOT_ACTIVE: "USER_NOT_ACTIVE",

  // 🔐 Authentication & Authorization
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",

  ACCESS_FORBIDDEN: "ACCESS_FORBIDDEN",
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",

  // 📍 Address
  ADDRESS_NOT_FOUND: "ADDRESS_NOT_FOUND",
  ADDRESS_CREATE_FAILED: "ADDRESS_CREATE_FAILED",
  ADDRESS_UPDATE_FAILED: "ADDRESS_UPDATE_FAILED",

  // 📄 Verification Documents
  VERIFICATION_DOCUMENT_FAILED: "VERIFICATION_DOCUMENT_FAILED",
  VERIFICATION_DOCUMENT_NOT_FOUND: "VERIFICATION_DOCUMENT_NOT_FOUND",
  VERIFICATION_EMAIL_FAILED: "VERIFICATION_EMAIL_FAILED",
  VERIFICATION_PHONE_FAILED: "VERIFICATION_PHONE_FAILED",
  VERIFICATION_NIN_FAILED: "VERIFICATION_NIN_FAILED",
  VERIFICATION_BVN_FAILED: "VERIFICATION_BVN_FAILED",
  VERIFICATION_DRIVERS_LICENSE_FAILED: "VERIFICATION_DRIVERS_LICENSE_FAILED",
  VERIFICATION_PASSPORT_FAILED: "VERIFICATION_PASSPORT_FAILED",
  VERIFICATION_REJECTED: "VERIFICATION_REJECTED",

  // 📦 Listings
  LISTING_NOT_FOUND: "LISTING_NOT_FOUND",
  LISTING_ALREADY_EXISTS: "LISTING_ALREADY_EXISTS",
  LISTING_CREATE_FAILED: "LISTING_CREATE_FAILED",
  LISTING_UPDATE_FAILED: "LISTING_UPDATE_FAILED",
  LISTING_DELETE_FAILED: "LISTING_DELETE_FAILED",
  LISTING_IMAGE_UPLOAD_FAILED: "LISTING_IMAGE_UPLOAD_FAILED",
  INVALID_LISTING_TYPE: "INVALID_LISTING_TYPE",
  INVALID_CATEGORY: "INVALID_CATEGORY",

  // 🗂 Categories
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_CREATE_FAILED: "CATEGORY_CREATE_FAILED",
  CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",

  // 💳 Transactions (Escrow)
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",
  TRANSACTION_CREATE_FAILED: "TRANSACTION_CREATE_FAILED",
  TRANSACTION_UPDATE_FAILED: "TRANSACTION_UPDATE_FAILED",
  TRANSACTION_ALREADY_COMPLETED: "TRANSACTION_ALREADY_COMPLETED",
  TRANSACTION_ALREADY_EXISTS: "TRANSACTION_ALREADY_EXISTS",
  TRANSACTION_CANCELLED: "TRANSACTION_CANCELLED",
  TRANSACTION_PAYMENT_FAILED: "TRANSACTION_PAYMENT_FAILED",
  TRANSACTION_ESCROW_RELEASE_FAILED: "TRANSACTION_ESCROW_RELEASE_FAILED",
  TRANSACTION_ESCROW_FUNDING_FAILED: "TRANSACTION_ESCROW_FUNDING_FAILED",
  TRANSACTION_DELIVERY_FAILED: "TRANSACTION_DELIVERY_FAILED",
  TRANSACTION_REVIEW_NOT_ALLOWED: "TRANSACTION_REVIEW_NOT_ALLOWED",
  INVALID_TRANSACTION_STATUS: "INVALID_TRANSACTION_STATUS",

  // 💰 Payments
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_ALREADY_PROCESSED: "PAYMENT_ALREADY_PROCESSED",
  PAYMENT_REFUND_FAILED: "PAYMENT_REFUND_FAILED",
  PAYMENT_GATEWAY_ERROR: "PAYMENT_GATEWAY_ERROR",

  // 👛 Wallet
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_TRANSACTION_FAILED: "WALLET_TRANSACTION_FAILED",
  WALLET_INSUFFICIENT_FUNDS: "WALLET_INSUFFICIENT_FUNDS",
  WALLET_TRANSACTION_NOT_FOUND: "WALLET_TRANSACTION_NOT_FOUND",
  WALLET_TRANSACTION_PENDING: "WALLET_TRANSACTION_PENDING",

  // ↩️ Refunds
  REFUND_REQUEST_FAILED: "REFUND_REQUEST_FAILED",
  REFUND_NOT_FOUND: "REFUND_NOT_FOUND",
  REFUND_ALREADY_PROCESSED: "REFUND_ALREADY_PROCESSED",
  REFUND_AMOUNT_MISMATCH: "REFUND_AMOUNT_MISMATCH",

  // ⚖️ Disputes
  DISPUTE_NOT_FOUND: "DISPUTE_NOT_FOUND",
  DISPUTE_ALREADY_EXISTS: "DISPUTE_ALREADY_EXISTS",
  DISPUTE_ALREADY_CLOSED: "DISPUTE_ALREADY_CLOSED",
  DISPUTE_RESOLUTION_FAILED: "DISPUTE_RESOLUTION_FAILED",
  DISPUTE_EVIDENCE_FAILED: "DISPUTE_EVIDENCE_FAILED",
  DISPUTE_EVIDENCE_NOT_FOUND: "DISPUTE_EVIDENCE_NOT_FOUND",

  // 🔔 Notifications
  NOTIFICATION_SEND_FAILED: "NOTIFICATION_SEND_FAILED",
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",

  // 🏦 Bank Accounts (optional extension if using)
  BANK_ACCOUNT_NOT_FOUND: "BANK_ACCOUNT_NOT_FOUND",
  BANK_ACCOUNT_ALREADY_EXISTS: "BANK_ACCOUNT_ALREADY_EXISTS",
  BANK_ACCOUNT_UPDATE_FAILED: "BANK_ACCOUNT_UPDATE_FAILED",

  // ⚙️ System Settings
  SYSTEM_CONFIG_ERROR: "SYSTEM_CONFIG_ERROR",
  SYSTEM_SETTING_NOT_FOUND: "SYSTEM_SETTING_NOT_FOUND",

  // 📄 Documents (generic)
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DOCUMENT_UPLOAD_FAILED: "DOCUMENT_UPLOAD_FAILED",
  DOCUMENT_VERIFICATION_FAILED: "DOCUMENT_VERIFICATION_FAILED",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
